name: Release dotnet package
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          source-url: https://nuget.pkg.github.com/evilz/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build --c Release Fun2C/Fun2C.csproj
      - name: Create the package
        run: dotnet pack --c Release Fun2C/Fun2C.csproj
      - name: Publish the package to GPR
        run: dotnet nuget push Fun2C/bin/Release/*.nupkg