name: dotnet Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover -c Release --no-build --verbosity normal
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./Fun2C.Tests/coverage.opencover.xml
          flags: unittests # optional
          verbose: true # optional (default = false)